app/urls.py
from django.conf.urls import url
from app import views


urlpatterns = [
    url(r'^$',views.home,name='home'),   #首页
    # url(r'^market/$',views.market,name='marketbase'),
    # url(r'^market/(\d+)/$',views.market,name='market'),   #闪购
    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),
    # url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$',views.cart,name='cart'),   #购物车
    url(r'^mine/$',views.mine,name='mine'),   #我的
    url(r'^login/$',views.login,name='login'),   #登陆
    url(r'^logout/$', views.logout, name='logout'),  # 注销
    url(r'^register/$', views.register, name='register'),  # 注册
    url(r'^addcart/$', views.addcart, name='addcart'),  # 添加到购物车
    url(r'^checkemail/$', views.checkemail, name='checkemail'), # 账号验证
    url(r'^subcart/$', views.subcart, name='subcart'),  # 减购物车
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),  # 购物车商品选中
    url(r'^changecartall/$', views.changecartall, name='changecartall'),  # 全选/取消全选
    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),  # 订单详情
    url(r'returnurl/$', views.returnurl, name='returnurl'), # 支付完成后客户端显示
    url(r'appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'), #
    url(r'pay/$', views.pay, name='pay'),
    ]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url('admin/', admin.site.urls),
    url('^axf/', include('app.urls', namespace='axf'))
]

templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
登陆
{% endblock %}

{% block extcss %}
 <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}



{% block content %}
<!--<div class="login">-->
 <!--<div class="back">-->
            <!--<a href="{% url 'axf:mine' %}">-->
                <!--<span class=" glyphicon glyphicon-remove "></span>-->
            <!--</a>-->
 <!--</div>-->
<!--<form action="{% url 'axf:login' %}" method="post">-->
 <!--{% csrf_token %}-->
 <!--<div class="input-group">-->
  <!--<span class="input-group-addon">帐号</span>-->
  <!--<input type="text" class="form-control" placeholder="请输入帐号" name="email">-->
 <!--</div>-->
    <!--<p style="color: red">{{ user_err }}</p>-->


 <!--<div class="input-group">-->
  <!--<span class="input-group-addon">密码</span>-->
  <!--<input type="password" class="form-control" placeholder="请输入密码" name="password">-->
 <!--</div>-->
    <!--<p style="color: red">{{ ps_err }}</p>-->

  <!--<input type="submit" value="登陆" id="subButton">-->
<!--</form>-->
<!--</div>-->

<div class="login">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class=" glyphicon glyphicon-remove "></span>
            </a>
        </div>

        <form action="{% url 'axf:login' %}" method="post">
            {% csrf_token %}

            <div class="input-group">
                <span class="input-group-addon">邮箱</span>
                <input type="text" class="form-control" placeholder="163邮箱/QQ邮箱.." name="email" required>
            </div>
            <p style="color: red;">
                {{ user_err }}
            </p>

            <div class="input-group">
                <span class="input-group-addon">密码</span>
                <input type="password" class="form-control" placeholder="6~10位数密码" name="password" required>
            </div>
            <p style="color: red">
                {{ ps_err }}
            </p>

            <input type="submit" value="登录" id="subButton">
        </form>
    </div>

{% endblock %}

{% block extjs %}
<script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
我的
{% endblock %}

{% block extcss %}
 <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}



{% block content %}
<div class="mine">
 <div class="user-wrapper">
  <div class="user-img">
   <img src="/static/mine/img/{{ user.img | default:"axf.png" }}" alt="">
  </div>
  <div class="user-content">
   <p>
    <span class="glyphicon glyphicon-user"></span>
    <a id="login-i">{{ user.name | default:'未登陆' }}</a>
   </p>
   <p>
    <span class="glyphicon glyphicon-flash"></span>
   等级:无
   </p>
   <a href="{% url 'axf:register' %}" class="register">注册</a>
  </div>
 </div>

 <div class="collect">
  <span class="glyphicon glyphicon-heart">

  </span>
  <i>商品收藏</i>
 </div>

 <section class="other">
  <section class="my">
   <span>我的订单</span>
   <a href="{% url 'axf:orderlist' %}">查看全部订单
    <i class="glyphicon glyphicon-chevron-right"></i></a>
  </section>

  <section>
   <ul>
    <li>
     <dl>
      <dt class="item">
       <span class="glyphicon glyphicon-usd"></span>
      <span class="badge">{{ waitpay }}</span>
      <dd>待付款</dd>

      </dt>
     </dl>
    </li>
    <li>
     <dl>
      <dt class="item">
       <span class="glyphicon glyphicon-envelope"></span>
      <span class="badge">{{ paydone }}</span>
      <dd>待收货</dd>

      </dt>
     </dl>
    </li>
    <li>
     <dl>
      <dt>
      <span class="glyphicon glyphicon-pencil">
      <dd>待评价</dd>
      </span>
      </dt>
     </dl>
    </li>
    <li>
     <dl>
      <dt>
      <span class="glyphicon glyphicon-retweet">
      <dd>退款/售后</dd>
      </span>
      </dt>
     </dl>
    </li>

   </ul>
  </section>

  <section>
   <ul>
    <li>
     <dl>
      <dt>
      <span class="glyphicon glyphicon-credit-card">
      <dd>优惠券</dd>
      </span>
      </dt>
     </dl>
    </li>
    <li>
     <dl>
      <dt>
      <span class="glyphicon glyphicon-home">
      <dd>收获地址</dd>
      </span>
      </dt>
     </dl>
    </li>
    <li>
     <dl>
      <dt>
      <span class="glyphicon glyphicon-phone-alt">
      <dd>客服/反馈</dd>
      </span>
      </dt>
     </dl>
    </li>
    <li>
     <dl>
      <dt>
      <span class="glyphicon glyphicon-certificate">
      <dd>关于我们</dd>
      </span>
      </dt>
     </dl>
    </li>

   </ul>
  </section>

 {% if user %}
  <section class="quit">
   <a href="{% url 'axf:logout' %}">退出</a>
  </section>
 {% endif %}
 </section>
</div>

{% endblock %}

{% block extjs %}
<script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
注册
{% endblock %}

{% block extcss %}
 <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{% endblock %}



{% block content %}
<!--<div class="register">-->
 <!--<div class="back">-->
            <!--<a href="{% url 'axf:mine' %}">-->
                <!--<span class=" glyphicon glyphicon-remove "></span>-->
            <!--</a>-->
 <!--</div>-->
<!--<form action="{% url 'axf:register' %}" method="post">-->
 <!--{% csrf_token %}-->
 <!--<div class="input-group">-->
  <!--<span class="input-group-addon">邮箱</span>-->
  <!--<input type="text" class="form-control" placeholder="邮箱.." name="email">-->
 <!--</div>-->

    <!--<div class="form-group has-feedback" id="email">-->
        <!--<div class="input-group">-->
            <!--<span class="input-group-addon">邮箱</span>-->


            <!--<input type="text" class="form-control" placeholder="163邮箱/QQ邮箱.." name="email" id="email-t"-->
                   <!--data-toggle="popover" data-placement="bottom"-->
                   <!--data-content="格式不正确">-->

        <!--</div>-->
    <!---->
    <!---->
    <!---->
 <!--<div class="input-group">-->
  <!--<span class="input-group-addon">密码</span>-->
  <!--<input type="password" class="form-control" placeholder="密码" name="password">-->
 <!--</div>-->

 <!--<div class="input-group">-->
  <!--<span class="input-group-addon">确认密码</span>-->
  <!--<input type="password" class="form-control" placeholder="确认密码" >-->
 <!--</div>-->

  <!--<div class="input-group">-->
  <!--<span class="input-group-addon">昵称</span>-->
  <!--<input type="text" class="form-control" placeholder="昵称" name="name">-->
 <!--</div>-->

 <!--<input type="submit" value="注册" id="subButton">-->


<!--</form>-->
<!--</div>-->

 <div class="register">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class=" glyphicon glyphicon-remove "></span>
            </a>
        </div>

        <form action="{% url 'axf:register' %}" method="post">
            {% csrf_token %}


            <div class="form-group has-feedback" id="email">
                <div class="input-group">
                    <span class="input-group-addon">邮箱</span>


                    <input type="text" class="form-control" placeholder="163邮箱/QQ邮箱.." name="email" id="email-t"
                           data-toggle="popover" data-placement="bottom"
                           data-content="格式不正确">

                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>


            <div class="form-group has-feedback" id="password">
                <div class="input-group">
                    <span class="input-group-addon">密码</span>
                    <input type="password" class="form-control" placeholder="6~10位数密码" name="password">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>


            <div class="form-group has-feedback" id="password-d">
                <div class="input-group">
                    <span class="input-group-addon">确认密码</span>
                    <input type="password" class="form-control" placeholder="6~10位数密码" id="password-t"
                           tabindex="0" data-toggle="popover" data-trigger="focus" data-placement="bottom"
                           data-content="两次密码不一致">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>


            <div class="form-group has-feedback" id="name">
                <div class="input-group">
                    <span class="input-group-addon">昵称</span>
                    <input type="text" class="form-control" placeholder="3~10位数(昵称)" name="name">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>

{#             submit按钮有特殊功能，提交功能#}
{#            <input type="submit" value="注册" id="subButton" disabled class="form-control">#}
        </form>

        <button id="subButton">注册</button>
    </div>
{% endblock %}

{% block extjs %}
<script src="{% static 'mine/js/register.js' %}"></script>
{% endblock %}

{% block footer %}
{% endblock %}